server {
    listen 80;

    server_name localhost;

    # Proxy requests to the Gramps frontend
    location / {
        proxy_pass http://gramps-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy requests to the Gramps API
    location /api/ {
        proxy_pass http://gramps-api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
